[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "CQrTMAMnm2p7EdRvctdFFqbtnhpAhfmPU32FPogQrfbf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/glaksmono/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
